### ISSUE TITLE
Jarvis (v16) 인스톨 관련

### ISSUE THREAD

**Issue by wyim-pgl** [hojel/xbmc-korea-addons#1]
안녕하세요 

만들어주신 Addon 잘 쓰고 있는 유저입니다.

1 .다름이 아니라 ondemandkorea를 사용하고 싶은데 tvaddons 를 이용해서 addon을 설치를 하게되면 설치는 되지만 실행이 되질 않고
1. github에 있는 zip 파일을 이용해서 설치하려면 설치가 되질 않습니다.

1번의 경우엔 드라마랑 다른 목록이 나오지만 클릭하게되면 에러가 나옵니다. 

2.번의 경우는 failed to install zip file로 나옵니다. 

혹시 예상되시는 문제가 있으시면 알려주시면 확인해 보겠습니다.

감사합니다.

**Comment by wyim-pgl** [comment]
잘됩니다. 감사합니다.

한가지더 질문이 있습니다만

디폴트로 480으로 되어 있는데 

옵션에서 720으로 바꾸어도 바뀌질 않습니다. 

비트레이트를 갖고오는데 문제가 있는것 같습니다.

감사합니다.

**Comment by hojel** [comment]
지금 기본 플레이 방식은 mp4인데 ios 전용입니다. 원래 360p 고정이였다가 480p로 바뀌었고, 파라미터로 변경되던게 지금은 지원이 안되는 모양입니다. 그냥 쓰셔야 겠네요.

**Comment by wyim-pgl** [comment]
네 감사합니다.
