### ISSUE TITLE
Ondemand Korea

### ISSUE THREAD

**Issue by i3un9** [hojel/xbmc-korea-addons#4]
The VODs are not loading and is getting a error message.
Any way to fix this? May be because of a redesign on their website.

**Comment by mistercorea** [comment]
I have a fixed zip for this.
for not I have did a pull quest but mean while you can use my zip.

https://github.com/mistercorea/xbmc-korea-addons/blob/master/download/plugin.video.ondemandkorea/plugin.video.ondemandkorea-0.5.1.zip

**Comment by Soul2Tech** [comment]
The zip won't install. Any new updates? Or can you repost the new zip

**Comment by i3un9** [comment]
0.5.1 stopped working. Any fix for this?

**Comment by MJC576** [comment]
0.5.1 hasn't worked this last week.  Here's the error log.  Any help is appreciated. 
T:948  ERROR: Unable to find plugin
T:6744  ERROR: XFILE::CDirector:GetDirectory - Error getting plugin://
T:6744  ERROR: CGUIMediaWIndow::GetDirectory(plugin://) failed

**Comment by mistercorea** [comment]
LOL nobody is fixing or patching this.

**Comment by i3un9** [comment]
0.5.3 is not working again. Please help.

**Comment by MJC576** [comment]
5.3 works great.
