### ISSUE TITLE
Ondemand Korea 5.0 not working.

### ISSUE THREAD

**Issue by MJC576** [hojel/xbmc-korea-addons#6]
Ondemand Korea has reorganized the sites and videos do not link correctly.    Can anyone help?

**Comment by mistercorea** [comment]
I have a fixed zip  for this.
for not I have did a pull quest but mean while you can use my zip.

https://github.com/mistercorea/xbmc-korea-addons/blob/master/download/plugin.video.ondemandkorea/plugin.video.ondemandkorea-0.5.1.zip

**Comment by MJC576** [comment]
Thank you It works great!

**Comment by mistercorea** [comment]
Can  you close the issue please?
